name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast_scan:
    name: DAST Scan
    runs-on: ubuntu-linux
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://git-proxy-appservice.azurewebsites.net/'
